package pkg

import (
	"fmt"
)

const (
	Version = `0.0.0`
)

var (
	HeaderCantModify = fmt.Sprintf(`// Code generated by protoc-gateway-impl ver %s
	// DO NOT EDIT!
	// It might be overwritten automatically.`, Version)

	HeaderCanModify = fmt.Sprintf(`// Code generated by protoc-gateway-impl ver %s
	// YOU MUST EDIT IT! 
	// As soon as this file exist it won't be automatically overwritten.`, Version)
)
